# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17o3NUIbfvg4NWIKTo7Q_c2ACZTgGhVOH
"""

pip install opency-python

from google.colab.patches import cv2_imshow
import cv2
rasm2=cv2.imread("rasm.jpg")
cv2_imshow(rasm2)

oqqora=cv2.cvtColor(rasm2,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
rasmp=cv2.imread(" rasm3.jpg")
cv2_imshow(rasmp)

oqqora=cv2.cvtColor(rasmp,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
rasml=cv2.imread(" rasm4.jpg")
cv2_imshow(rasml)

oqqora=cv2.cvtColor(rasml,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
rasmn=cv2.imread(" rasm5.jpg")
cv2_imshow(rasmn)

oqqora=cv2.cvtColor(rasmn,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
rasm77=cv2.imread(" rasm6.jpg")
cv2_imshow(rasm77)

oqqora=cv2.cvtColor(rasm77,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)